name: 'Container CI'



# trigger
on:
  
  # pipeline de integracao sera executada quando houver algum push
  # envolvendo o diretorio app1 na branch main
  push:
    branches:
      - main
    paths:
      - app1/**
  
  pull_request: # [master, next]
    paths:
      - app1/**




# atividades
jobs:

  # cria container
  container:
    name: 'Container'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: app1 # especifica diretorio
        shell: bash

    steps:

    - if: github.event_name == 'pull_request'
      name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v3 
      with:
        token: ${{secrets.github_token}}    
   
   
    - name: Check Out Repo 
      if: github.event_name == 'pull_request'
      uses: actions/checkout@v2


    - name: Login to Docker Hub
      if: github.event_name == 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


    - name: Set up Docker Buildx
      if: github.event_name == 'pull_request'
      id: buildx
      uses: docker/setup-buildx-action@v1


    - name: Build and push
      if: github.event_name == 'pull_request'
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./app1/container
        file: ./app1/container/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/app1:${{ steps.buildnumber.outputs.build_number }}
